### ISSUE TITLE
Trying to reproduce some result from the paper

### ISSUE THREAD

**Issue by IlyaTrofimov** [yandex-research/rtdl-num-embeddings#21]
Hi!

I'm trying to reproduce numbers from Table 4 in https://arxiv.org/pdf/2203.05556.
For California Housing there should be 0,439 for MLP-T-LR.
When I use hyperparameter from https://github.com/yandex-research/rtdl-num-embeddings/blob/abf8a8b35854e4b06476bb48902096b0b58ffce2/exp/mlp-t-lr/california/0_tuning/report.json

I get around ~0.45 at test dataset for various seeds.
Can you please spot the problem?

**Comment by Yura52** [comment]
Hi! Unfortunately, I cannot replicate the environment on my current machine to confirm the issue. Have you tried retuning the hyperparameters from scratch, and evaluating the newly tuned hyperparameters? Sometimes, tuning hyperparameters in one environment and evaluating them in a different environment can result in metric fluctuations.

**Comment by Yura52** [comment]
Feel free to reopen the issue if needed! Also, I recommend taking a look at the updated piecewise-linear embeddings available in the package `rtdl_num_embeddings` since v0.0.11: [link](https://github.com/yandex-research/rtdl-num-embeddings/releases/tag/v0.0.11).
