### ISSUE TITLE
bin/results.ipynb is missing

### ISSUE THREAD

**Issue by isCopyman** [yandex-research/rtdl-num-embeddings#22]
In readme.md, there is "# Then use bin/results.ipynb to view the obtained results"
But I can't find the bin/results.ipynb in this Repository

**Comment by Yura52** [comment]
Thanks for reporting the issue! Indeed, at some point, the notebook was removed, but is still mistakengly mentioned in some places. The current recommended way to explore results is [this section](https://github.com/yandex-research/rtdl-num-embeddings?tab=readme-ov-file#how-to-explore-metrics-and-hyperparameters).
